name: adblock

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Delete previous workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PREVIOUS_RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs" | jq -r '.workflow_runs[] | select(.status == "completed") | .id')
          for run_id in $PREVIOUS_RUNS; do
            echo "Deleting workflow run ID: $run_id"
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done

      - name: oisd
        run: |
          echo "Downloading oisd big block list..."
          curl -s 'https://big.oisd.nl/domainswild' -o oisd_big_domainswild.txt
          awk '/^\*\./ && !x {print "payload:"; x=1} 1' oisd_big_domainswild.txt > oisd_big.yaml
          sed -i 's/^[*]\./  - DOMAIN-SUFFIX,/g' oisd_big.yaml
          rm -fr oisd_big_domainswild.txt

      - name: pro
        run: |
          echo "Downloading hagezi pro block list..."
          curl -s 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.plus.txt' -o pro.plus.txt
          awk 'BEGIN {header_inserted=0} 
               /^#/ { 
                 print; 
                 if($0=="#" && header_inserted==0) { 
                   print "payload:"; 
                   header_inserted=1 
                 } 
                 next 
               } 
               {print "  - DOMAIN-SUFFIX," $0}' pro.plus.txt > pro.plus.yaml
          rm -f pro.plus.txt

      - name: tif
        run: |
          echo "Downloading hagezi tif block list..."
          curl -s 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/tif.txt' -o tif.txt
          awk 'BEGIN {header_inserted=0} 
               /^#/ { 
                 print; 
                 if($0=="#" && header_inserted==0) { 
                   print "payload:"; 
                   header_inserted=1 
                 } 
                 next 
               } 
               {print "  - DOMAIN-SUFFIX," $0}' tif.txt > tif.yaml
          rm -f tif.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
